export const CODE_FONT_STYLE = {
  fontFamily: "'JetBrains Mono', monospace",
  fontVariantLigatures: 'none',
  fontFeatureSettings: '"liga" 0, "calt" 0',
}

export const s = {
  wrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    maxWidth: 1120,
    margin: '0 auto',
  },
  optionsSection: {
    border: '1px solid var(--ui-border)',
    borderRadius: 8,
    overflow: 'hidden',
    background: '#fff',
    boxShadow: '0 5px 16px rgba(40, 22, 78, 0.06)',
  },
  optionsSectionToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '12px 14px',
    background: 'linear-gradient(180deg, #ffffff 0%, var(--ui-surface-soft) 100%)',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    boxShadow: 'none',
  },
  optionsSectionTitle: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
    flexShrink: 0,
  },
  optionsSummaryText: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    color: '#6b7280',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  optionsChevron: {
    marginLeft: 'auto',
    color: 'var(--colour-primary)',
    fontSize: '1rem',
    lineHeight: 1,
    flexShrink: 0,
    transition: 'transform 0.15s ease',
  },
  optionsBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    padding: '16px',
    borderTop: '1px solid var(--ui-border)',
    background: '#fff',
  },
  input: {
    padding: '8px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
    color: 'var(--colour-text)',
    outline: 'none',
    width: '100%',
  },
  autoTitleBadge: {
    fontSize: '0.75rem',
    fontFamily: 'var(--font-body)',
    color: 'var(--colour-primary)',
    opacity: 0.6,
    flexShrink: 0,
    userSelect: 'none',
  },
  resetTitleBtn: {
    fontSize: '0.75rem',
    fontFamily: 'var(--font-body)',
    color: 'var(--colour-primary)',
    background: 'transparent',
    border: '1px solid #c4b5fd',
    borderRadius: 4,
    padding: '3px 7px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  select: {
    padding: '7px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
    background: '#fff',
    cursor: 'pointer',
    outline: 'none',
  },
  checkToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.88rem',
    cursor: 'pointer',
  },
  checkRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
  },
  checkIndexLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.8rem',
    color: '#6b7280',
    paddingTop: 10,
    minWidth: 22,
    textAlign: 'right',
  },
  removeCheckBtn: {
    marginTop: 8,
    flexShrink: 0,
    width: 28,
    height: 28,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#fff',
    color: '#6b7280',
    cursor: 'pointer',
    fontSize: '1rem',
    lineHeight: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addCheckBtn: {
    alignSelf: 'flex-start',
    color: 'var(--colour-primary)',
    border: '1px solid var(--colour-primary)',
    padding: '6px 12px',
    fontSize: '0.83rem',
  },
  checkEditor: {
    display: 'grid',
    gridTemplateColumns: 'max-content max-content minmax(0, 1fr)',
    gap: 8,
    alignItems: 'start',
    flex: 1,
  },
  checkValue: {
    padding: '8px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    ...CODE_FONT_STYLE,
    fontSize: '0.9rem',
    lineHeight: 1.5,
    color: 'var(--colour-text)',
    outline: 'none',
    width: '100%',
    minHeight: 92,
    resize: 'vertical',
    whiteSpace: 'pre-wrap',
  },
  checkHelp: {
    padding: '8px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    color: '#4b5563',
    background: '#f9fafb',
  },
  hintsEditor: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    padding: 10,
  },
  hintsEmpty: {
    margin: 0,
    color: '#9ca3af',
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
  },
  hintRow: {
    display: 'grid',
    gridTemplateColumns: '72px minmax(0, 1fr) 28px',
    gap: 8,
    alignItems: 'start',
  },
  hintIndex: {
    paddingTop: 9,
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    fontWeight: 700,
    color: 'var(--colour-primary)',
  },
  hintInput: {
    padding: '8px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
    color: 'var(--colour-text)',
    outline: 'none',
    resize: 'vertical',
    minHeight: 38,
    lineHeight: 1.45,
  },
  addHintBtn: {
    alignSelf: 'flex-start',
    color: 'var(--colour-primary)',
    border: '1px dashed var(--colour-primary)',
    padding: '6px 12px',
    fontSize: '0.83rem',
  },
  quizOptions: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  quizTypeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 10,
  },
  quizTypeBtn: {
    minHeight: 92,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: '12px 8px',
    border: '2px solid #e5e7eb',
    borderRadius: 10,
    background: '#fff',
    color: 'var(--colour-primary)',
    cursor: 'pointer',
    transition: 'border-color 0.12s, background 0.12s, color 0.12s',
  },
  quizTypeBtnActive: {
    borderColor: 'var(--colour-primary)',
    background: 'var(--colour-primary)',
    color: '#fff',
  },
  quizTypeLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.82rem',
    lineHeight: 1.1,
    textAlign: 'center',
  },
  quizTypeMeta: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.72rem',
    lineHeight: 1.2,
    color: '#6b7280',
    textAlign: 'center',
  },
  quizTypeMetaActive: {
    color: 'rgba(255, 255, 255, 0.82)',
  },
  quizOptionCard: {
    display: 'grid',
    gridTemplateColumns: '116px minmax(0, 1fr) 32px',
    gap: 10,
    alignItems: 'start',
    padding: 10,
    border: '1px solid var(--ui-border)',
    borderRadius: 8,
    background: 'var(--ui-surface-soft)',
  },
  quizCorrectLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 7,
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    color: 'var(--colour-text)',
    cursor: 'pointer',
    paddingTop: 2,
  },
  quizOptionId: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: 'var(--colour-primary)',
    color: '#fff',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  quizCorrectPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    minHeight: 24,
    padding: '4px 8px',
    border: '1px solid var(--ui-border)',
    borderRadius: 999,
    background: '#fff',
    color: '#6b7280',
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.72rem',
    lineHeight: 1,
  },
  quizCorrectPillActive: {
    borderColor: '#22c55e',
    background: '#f0fdf4',
    color: '#15803d',
  },
  quizOptionEditor: {
    minWidth: 0,
  },
  quizAnswerStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  quizAnswerCard: {
    display: 'grid',
    gridTemplateColumns: '34px minmax(0, 1fr) 32px',
    gap: 10,
    alignItems: 'start',
    padding: 10,
    border: '1px solid var(--ui-border)',
    borderRadius: 8,
    background: 'var(--ui-surface-soft)',
  },
  quizAnswerBadge: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: 'var(--colour-primary)',
    color: '#fff',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    fontSize: '0.86rem',
  },
  quizAnswerEditorBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  quizAnswerLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.76rem',
    color: 'var(--colour-primary)',
  },
  matchPairEditorRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 20px minmax(0, 1fr)',
    gap: 10,
    alignItems: 'start',
  },
  matchArrow: {
    alignSelf: 'center',
    justifySelf: 'center',
    width: 18,
    height: 2,
    borderRadius: 999,
    background: 'var(--ui-border-strong)',
    color: 'transparent',
    userSelect: 'none',
  },
  scratchCheckEditor: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: 8,
    alignItems: 'start',
    marginTop: 8,
  },
  collapsibleField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    overflow: 'hidden',
    background: '#fff',
  },
  collapsibleHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '12px 14px',
    border: 0,
    background: 'transparent',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
  },
  collapsibleLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
  },
  collapsibleChevron: {
    fontSize: '1rem',
    color: '#6b7280',
    transition: 'transform 0.15s ease',
    lineHeight: 1,
  },
  toolboxPicker: {
    borderTop: '1px solid #e5e7eb',
    background: '#fff',
    overflow: 'hidden',
  },
  toolboxAllRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 14px',
    borderBottom: '1px solid #e5e7eb',
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
    fontWeight: 700,
    color: 'var(--colour-text)',
    cursor: 'pointer',
  },
  toolboxGroups: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))',
    gap: 12,
    padding: 14,
  },
  toolboxDisabled: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))',
    gap: 12,
    padding: 14,
    opacity: 0.5,
  },
  toolboxGroup: {
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    overflow: 'hidden',
    background: '#fafafa',
  },
  toolboxGroupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderBottom: '1px solid #e5e7eb',
    background: '#fff',
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    fontWeight: 700,
    color: 'var(--colour-text)',
    cursor: 'pointer',
  },
  toolboxGroupSwatch: {
    width: 10,
    height: 10,
    borderRadius: '50%',
    flexShrink: 0,
  },
  toolboxBlockGrid: {
    display: 'grid',
    gap: 6,
    padding: 10,
  },
  toolboxBlockItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontFamily: 'var(--font-body)',
    fontSize: '0.83rem',
    lineHeight: 1.35,
    color: '#374151',
    cursor: 'pointer',
  },
  scratchPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    height: 560,
    minHeight: 480,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    padding: 12,
  },
  scratchWorkspaceWrap: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  scratchCheckPass: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    fontWeight: 700,
    color: '#166534',
    background: '#dcfce7',
    border: '1px solid #bbf7d0',
    borderRadius: 999,
    padding: '4px 10px',
  },
  scratchCheckFail: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    fontWeight: 700,
    color: '#92400e',
    background: '#fffbeb',
    border: '1px solid #fde68a',
    borderRadius: 999,
    padding: '4px 10px',
  },
  starterBlocksSummary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    padding: '14px 16px',
    background: '#fff',
  },
  summaryText: {
    margin: '4px 0 0',
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    lineHeight: 1.45,
    color: '#6b7280',
  },
  secondaryBtn: {
    color: 'var(--colour-primary)',
    border: '1px solid var(--colour-primary)',
    padding: '8px 14px',
    fontSize: '0.86rem',
    whiteSpace: 'nowrap',
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 40,
    background: 'rgba(17, 24, 39, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modal: {
    width: 'min(1400px, 97vw)',
    height: 'min(900px, 93vh)',
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 24px 70px rgba(0, 0, 0, 0.28)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  modalHeader: {
    height: 50,
    padding: '0 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #e5e7eb',
    background: '#fafafa',
    flexShrink: 0,
  },
  modalTitle: {
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    color: 'var(--colour-text)',
  },
  closeBtn: {
    width: 32,
    height: 32,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#fff',
    color: '#374151',
    cursor: 'pointer',
    fontSize: '1rem',
    lineHeight: 1,
  },
  modalBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    padding: 14,
  },
  scratchModalContent: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  scratchModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexShrink: 0,
  },
  scratchModalBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    overflow: 'hidden',
  },
  scratchConfigSidebar: {
    width: 300,
    flexShrink: 0,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    borderRight: '1px solid #e5e7eb',
    background: '#fafafa',
    padding: '12px 10px',
  },
  scratchModalWorkspace: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    overflow: 'hidden',
  },
  sidebarSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  sidebarSectionTitle: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.78rem',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    paddingBottom: 4,
    borderBottom: '1px solid #e5e7eb',
  },
  divider: {
    height: 1,
    background: '#e5e7eb',
    margin: '4px 0',
  },
  workspaceTabs: {
    display: 'flex',
    gridTemplateColumns: '1fr 1fr',
    gap: 4,
    alignSelf: 'stretch',
    width: '100%',
    border: '1px solid #e5e7eb',
    borderBottom: 0,
    borderRadius: '8px 8px 0 0',
    padding: '4px 4px 0',
    background: '#e5e7eb',
  },
  workspaceTab: {
    border: 0,
    borderRadius: '6px 6px 0 0',
    background: 'transparent',
    color: '#4b5563',
    padding: '8px 12px',
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    fontWeight: 700,
    cursor: 'pointer',
  },
  workspaceTabActive: {
    background: '#fafafa',
    color: 'var(--colour-primary)',
  },
  workspaceTabActions: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: 8,
  },
  workspaceTabAdd: {
    border: 0,
    borderRadius: '6px 6px 0 0',
    background: 'transparent',
    color: '#6b7280',
    padding: '8px 10px',
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  stageRemoveBtn: {
    border: 0,
    background: 'transparent',
    color: '#9ca3af',
    cursor: 'pointer',
    fontSize: '0.7rem',
    padding: '2px 3px',
    lineHeight: 1,
    marginLeft: -4,
    marginRight: 2,
  },
  codeWorkspaceStack: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    gap: 0,
  },
  pythonEditor: {
    height: 300,
    border: '1px solid #e5e7eb',
    borderRadius: '0 0 8px 8px',
    overflow: 'hidden',
  },
  attachedCodeEditor: {
    borderRadius: '0 0 8px 8px',
  },
  runRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  previewPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minHeight: 420,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    padding: 12,
  },
  infoNotice: {
    border: '1px solid #d8b4fe',
    borderRadius: 8,
    background: '#f5f3ff',
    color: 'var(--colour-primary)',
    padding: '12px 14px',
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
    fontWeight: 600,
    lineHeight: 1.5,
  },
  previewHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  previewTitle: {
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    fontSize: '0.9rem',
    color: 'var(--colour-text)',
  },
  previewFrame: {
    flex: 1,
    minHeight: 320,
    overflow: 'hidden',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
  },
  htmlSplit: {
    display: 'flex',
    flexDirection: 'column',
    height: 430,
    gap: 0,
    width: '100%',
    minWidth: 0,
  },
  htmlSplitHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexShrink: 0,
  },
  htmlSplitLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
    flexShrink: 0,
  },
  htmlEditorWithRail: {
    display: 'flex',
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
    gap: 8,
  },
  htmlLeft: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    gap: 0,
  },
  htmlEditorPane: {
    display: 'flex',
    flex: 1,
    width: '100%',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  htmlCodeEditor: {
    width: '100%',
    minWidth: 0,
    flex: '1 1 auto',
    borderRadius: '0 0 8px 8px',
  },
  builderPreviewPane: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
    gap: 10,
  },
  previewRail: {
    width: 44,
    minWidth: 44,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: 'var(--colour-primary)',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '10px 0',
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
  },
  previewRailIcon: {
    fontSize: 22,
    lineHeight: 1,
  },
  previewRailLabel: {
    writingMode: 'vertical-rl',
    transform: 'rotate(180deg)',
    fontSize: '0.74rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  noFile: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#9ca3af',
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
  },
  spriteManager: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 12,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fafafa',
  },
  spriteRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  costumeToggleBtn: {
    padding: '4px 8px',
    fontSize: '0.78rem',
    fontFamily: 'var(--font-body)',
    border: '1px solid #e5e7eb',
    borderRadius: 4,
    background: '#fff',
    cursor: 'pointer',
    color: '#6b7280',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  costumeManager: {
    marginLeft: 8,
    marginTop: 2,
    marginBottom: 4,
    padding: '10px 12px',
    background: '#f5f3ff',
    border: '1px dashed #c4b5fd',
    borderRadius: 6,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  costumeBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  costumeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  costumeTag: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.72rem',
    fontWeight: 700,
    color: 'var(--colour-primary)',
    background: '#f3eeff',
    border: '1px solid #e9d5ff',
    borderRadius: 4,
    padding: '2px 6px',
    flexShrink: 0,
  },
  costumeThumb: {
    width: 32,
    height: 32,
    objectFit: 'contain',
    borderRadius: 4,
    border: '1px solid #e5e7eb',
    flexShrink: 0,
    background: '#fff',
  },
  costumeEmpty: {
    margin: 0,
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    color: '#9ca3af',
    lineHeight: 1.4,
  },
  spriteField: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  spriteFieldLabel: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.78rem',
    color: '#6b7280',
    fontWeight: 600,
    whiteSpace: 'nowrap',
  },
  removeBtn: {
    width: 28,
    height: 28,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#fff',
    cursor: 'pointer',
    fontSize: '0.8rem',
    color: '#9ca3af',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  addSpriteBtn: {
    alignSelf: 'flex-start',
    fontSize: '0.83rem',
    padding: '6px 12px',
    color: 'var(--colour-primary)',
    border: '1px dashed var(--colour-primary)',
    borderRadius: 6,
    background: 'transparent',
    cursor: 'pointer',
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
  },
  backdropManager: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 12,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fafafa',
  },
  backdropBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  backdropRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  browseToggleBtn: {
    padding: '4px 10px',
    fontSize: '0.78rem',
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    border: '1px solid var(--colour-primary)',
    borderRadius: 4,
    background: 'transparent',
    color: 'var(--colour-primary)',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  browseToggleBtnActive: {
    background: 'var(--colour-primary)',
    color: '#fff',
  },
  inlineBrowser: {
    maxHeight: 160,
    overflowY: 'auto',
    borderRadius: 4,
  },
  backdropTag: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.72rem',
    fontWeight: 700,
    color: 'var(--colour-primary)',
    background: '#f3eeff',
    border: '1px solid #e9d5ff',
    borderRadius: 4,
    padding: '2px 6px',
    flexShrink: 0,
  },
  backdropSwatch: {
    width: 28,
    height: 28,
    borderRadius: 5,
    border: '1px solid #e5e7eb',
    flexShrink: 0,
  },
  backdropThumb: {
    width: 40,
    height: 28,
    objectFit: 'cover',
    borderRadius: 4,
    border: '1px solid #e5e7eb',
    flexShrink: 0,
  },
  carryRadioGroup: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))',
    gap: 10,
  },
  carryRadioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontFamily: 'var(--font-body)',
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
    cursor: 'pointer',
  },
  carryRadioLabelDisabled: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontFamily: 'var(--font-body)',
    fontSize: '0.88rem',
    color: '#9ca3af',
    cursor: 'not-allowed',
  },
  carryNote: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    color: '#9ca3af',
  },
  optionChoiceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))',
    gap: 10,
  },
  optionChoiceCard: {
    minHeight: 76,
    display: 'grid',
    gridTemplateColumns: '18px minmax(0, 1fr)',
    columnGap: 10,
    rowGap: 3,
    alignItems: 'start',
    padding: '12px 14px',
    border: '2px solid #e5e7eb',
    borderRadius: 10,
    background: '#fff',
    color: 'var(--colour-text)',
    cursor: 'pointer',
    transition: 'border-color 0.12s, background 0.12s, color 0.12s',
  },
  optionChoiceCardActive: {
    borderColor: 'var(--colour-primary)',
    background: 'var(--colour-primary)',
    color: '#fff',
  },
  optionChoiceCardDisabled: {
    opacity: 0.52,
    cursor: 'not-allowed',
  },
  optionChoiceInput: {
    gridRow: '1 / span 2',
    marginTop: 2,
    accentColor: 'var(--colour-primary)',
  },
  optionChoiceTitle: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.86rem',
    lineHeight: 1.2,
  },
  optionChoiceText: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.76rem',
    lineHeight: 1.35,
    color: '#6b7280',
  },
  optionChoiceTextActive: {
    color: 'rgba(255, 255, 255, 0.82)',
  },
  optionToggleCard: {
    minHeight: 68,
    display: 'grid',
    gridTemplateColumns: '18px minmax(0, 1fr)',
    columnGap: 10,
    rowGap: 3,
    alignItems: 'start',
    padding: '12px 14px',
    border: '2px solid #e5e7eb',
    borderRadius: 10,
    background: '#fff',
    color: 'var(--colour-text)',
    cursor: 'pointer',
    transition: 'border-color 0.12s, background 0.12s, color 0.12s',
  },
  optionToggleCardActive: {
    borderColor: 'var(--colour-primary)',
    background: 'var(--colour-primary)',
    color: '#fff',
  },
  optionNote: {
    margin: 0,
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    color: '#6b7280',
    lineHeight: 1.5,
    padding: '0 2px',
  },
  colorInput: {
    width: 36,
    height: 28,
    padding: 2,
    border: '1px solid #e5e7eb',
    borderRadius: 5,
    cursor: 'pointer',
    flexShrink: 0,
  },
  taskFormatGrid: {
    display: 'flex',
    gap: 10,
  },
  infoTypeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 10,
  },
  infoTypeBtn: {
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    background: '#fff',
    color: 'var(--colour-text)',
    padding: '10px 12px',
    textAlign: 'left',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  },
  infoTypeBtnActive: {
    borderColor: 'var(--colour-primary)',
    background: '#f7f2ff',
    color: 'var(--colour-primary)',
  },
  infoTypeLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.9rem',
  },
  infoTypeHint: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.78rem',
    color: '#6b7280',
    lineHeight: 1.3,
  },
  infoPreview: {
    minHeight: 340,
    maxHeight: 520,
    display: 'flex',
    overflow: 'hidden',
    padding: 12,
    background: '#f5f5f5',
  },
  taskFormatBtn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '14px 8px',
    border: '2px solid #e5e7eb',
    borderRadius: 10,
    background: '#fff',
    color: 'var(--colour-primary)',
    cursor: 'pointer',
    transition: 'border-color 0.12s, background 0.12s, color 0.12s',
  },
  taskFormatBtnActive: {
    borderColor: 'var(--colour-primary)',
    background: 'var(--colour-primary)',
    color: '#fff',
  },
  taskFormatLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.82rem',
    lineHeight: 1,
  },
  variableRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  variableStageLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontFamily: 'var(--font-body)',
    fontSize: '0.78rem',
    fontWeight: 600,
    color: '#6b7280',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    flexShrink: 0,
  },
}
